
# Documentation
# https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
name: CICD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: 
      - "**"

jobs: 

  build:
    name: Compile and test
    
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Run NPM install
        run: npm install

      - name: Compile
        run: npm run 'compile'
      
      - name: Linter
        run: npm run lint

      - name: Test on Linux
        if: runner.os == 'Linux'
        run: xvfb-run -a npm run 'test'
      
      - name: Test on OS != Linux
        if: runner.os != 'Linux'
        run: npm run 'test'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref_name == 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
              fetch-depth: 0
              
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Run NPM install
        run: npm install

      - name: Configure Git
        run: |
          # 'github-actions[bot]@users.noreply.github.com' OR action@github.com OR 41898282+github-actions[bot]@users.noreply.github.com
          # from https://api.github.com/users/github-actions%5Bbot%5D
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          #'github-actions[bot]' OR "GitHub Action"
          git config --local user.name 'github-actions[bot]'

      #https://github.com/marketplace/actions/git-semantic-version
      - name: "Generate new version"
        uses: paulhatch/semantic-version@v4.0.2
        id: semantic-version
        with:
          tag_prefix: "v"
          major_pattern: "/((BREAKING CHANGE|major):?|\\S*!).*/"
          minor_pattern: "/(feature|minor|feat):?[^!].*/"
          format: "${major}.${minor}.${patch}"
          namespace: ""
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "csv"

      - run: echo version generated ${{ steps.semantic-version.outputs.version }}

      # https://code.visualstudio.com/api/working-with-extensions/publishing-extension#autoincrementing-the-extension-version
      - name: Publish to marketplace
        if: success()
        run: npm run publishVersion --newversion=${{ steps.semantic-version.outputs.version }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Push the new version & tag
        if: success()
        run: git push --follow-tags
